sudo: false

language: r
r:
  - oldrel
  - release
  - devel

cache: packages

install:
  - Rscript -e 'install.packages(c("devtools", "roxygen2", "testthat", "knitr", "rmarkdown")); devtools::install_deps()'
script:
  - Rscript -e 'devtools::check(manual = TRUE)'
  
r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'install.packages("covr"); covr::coveralls("pkg")'
